basic:
    name: 'https://chcf.org'
    environments:
        production: 'https://chcf.org'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 640
        - 760
        - 768
        - 1024
        - 1080
        - 1200
        - 1440
        - 1920
    pages:
        - /
        - /site-updates
        - /our-approach
        - /our-approach/goals-strategy
        - /our-approach/our-approach-to-health-equity
        - /our-priorities
        - /our-approach/learning-impact
        - /topics
        - /behavioral-health
        - /facts-and-data
        - /health-care-costs-affordability
        - /health-equity
        - /health-insurance-coverage
        - /network/chcf-health-care-leadership-program
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
