basic:
    name: 'https://chcf.org'
    environments:
        production: 'https://chcf.org'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /site-updates
        - /our-approach
        - /our-approach/goals-strategy
        - /our-approach/our-approach-to-health-equity
        - /our-priorities
        - /our-approach/learning-impact
        - /topics
        - /behavioral-health
        - /facts-and-data
        - /health-care-costs-affordability
        - /health-equity
        - /health-insurance-coverage
        - /network/chcf-health-care-leadership-program
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: "const list = document.querySelector('.jumplink-menu__list');\n\n  const links = list.querySelectorAll('a');\n\n  links.forEach((a, i) => {\n    const isFirst = i === 0;\n    a.classList.toggle('current', isFirst);\n    a.setAttribute('aria-current', String(isFirst));\n  });"
    custom_css: ".wp-embed-responsive .wp-has-aspect-ratio iframe {\n\tposition: unset !important;\n}"
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
